### ISSUE TITLE
TypeError: c.stack.forEach is not a function

### ISSUE THREAD

**Issue by btakita** [toolness/tap-prettify#3]
I'm redirecting the output from `tape-run` to `tap-prettify`. I inserted a `console.info(c.stack)`.

```
$ gulp test | ./node_modules/tap-prettify/bin/tap-prettify.js -
✓ login|render|GET https://accounts.crystalcommerce.com/account.json|401|show logged-out
x account/login/login.tag|main

  SyntaxError: JSON Parse error: Unexpected identifier "undefined" failure

  Traceback (most recent call first):
c.stack { 'at parse ([native code])': '',
  'at http': '//localhost:52950/bundle.js?daec7d24:26718:9',
  'at baseFindIndex (http': '//localhost:52950/bundle.js?daec7d24:5902:20)',
  'at request (http': '//localhost:52950/bundle.js?daec7d24:26769:20)',
  'at bound (http': '//localhost:52950/bundle.js?daec7d24:24630:37)',
  'at run (http': '//localhost:52950/bundle.js?daec7d24:2446:19)',
  'at next (http': '//localhost:52950/bundle.js?daec7d24:24440:18)',
  'at drainQueue (http': '//localhost:52950/bundle.js?daec7d24:2417:41)' }
/home/phoenix/workspace/cc/frontend-components/node_modules/tap-prettify/index.js:92
                c.stack.forEach(function(line) {
                        ^
TypeError: c.stack.forEach is not a function
    at /home/phoenix/workspace/cc/frontend-components/node_modules/tap-prettify/index.js:92:25
    at Array.forEach (native)
    at TapConsumer.<anonymous> (/home/phoenix/workspace/cc/frontend-components/node_modules/tap-prettify/index.js:78:32)
    at emitOne (events.js:82:20)
    at TapConsumer.emit (events.js:169:7)
    at TapConsumer._parseLine (/home/phoenix/workspace/cc/frontend-components/node_modules/tap-prettify/node_modules/tap/lib/tap-consumer.js:133:20)
    at TapConsumer.write (/home/phoenix/workspace/cc/frontend-components/node_modules/tap-prettify/node_modules/tap/lib/tap-consumer.js:77:10)
    at Socket.ondata (_stream_readable.js:521:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
stream.js:74
      throw er; // Unhandled stream error in pipe.
            ^
Error: write EPIPE
    at Object.exports._errnoException (util.js:812:11)
    at exports._exceptionWithHostPort (util.js:835:20)
    at WriteWrap.afterWrite (net.js:758:14)

```

**Comment by btakita** [comment]
It looks like `tap-prettify` uses an old version of `tap`, which uses a broken yaml parser.

**Comment by VannaDii** [comment]
Yeah, this is still an issue
